apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - log4net_config.yaml
  - ingress.yaml
  - pvclaim_aks.yaml
  - deployment.yaml
  - hpa.yaml
  - service.yaml
  
   
  
  
  
  
  
  
