apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

commonLabels:
  env: prod

resources:
  - namespace.yaml
  - ingress.yaml
  - pvclaim_aks.yaml
  - deployment.yaml
namespace: bold-services-prod